import Head from 'next/head'
import { Inter } from 'next/font/google'
import About from '@/components/About/About'
import Des from '@/components/Des/Des'
import Hero from '@/components/Hero/Hero'
import Product from '@/components/Product/Product'
import Info from '@/components/Info/Info'
import Login from '@/components/Autorization/Login'
import Register from '@/components/Autorization/Register'
const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login/>
      {/* <Register/> */}
      {/* <Hero/> */}
      {/* <About/> */}
      {/* <Des/> */}
      {/* <Info/> */}
    </>
  )
}
